name: Build and Publish

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Login to npm
        run: npm login --registry=https://registry.npmjs.org/ --always-auth --username=${{ secrets.NPM_USERNAME }} --password=${{ secrets.NPM_TOKEN }} --email=${{ secrets.NPM_EMAIL }}

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
